version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: bigdata
      POSTGRES_USER: llegat # feel free to change this
      POSTGRES_PASSWORD: tImPgDBfBDc!32# # feel free to change this
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: llegat@example.com # feel free to change this
      PGADMIN_DEFAULT_PASSWORD: tImPgDBfBDc!32# # feel free to change this
    ports:
      - "5050:80"
    networks:
      - pg-network

networks:
  pg-network:

volumes:
  pg-data: