version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres # use this as "Host name/address" when connecting a new pgadmin server
    environment:
      POSTGRES_DB: bigdata
      POSTGRES_USER: bigdata # feel free to change this
      POSTGRES_PASSWORD: tImPgDBfBDc!32# # feel free to change this
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: bigdata@example.com # feel free to change this
      PGADMIN_DEFAULT_PASSWORD: tImPgDBfBDc!32# # feel free to change this
    ports:
      - "5050:80"
    volumes:
      - ./data:/data